- id: '1546122961477'
  alias: New Automation
  trigger:
  - platform: webhook
    webhook_id: start-bob
  condition: []
  action:
  - data:
      entity_id: vacuum.bob
    service: vacuum.turn_on
- id: '1546123031690'
  alias: turn on bob
  trigger:
  - platform: webhook
    webhook_id: start bob
  condition: []
  action:
  - alias: ''
    data:
      entity_id: vacuum.bob
    service: vacuum.turn_on
- id: '1546123118519'
  alias: New Automation
  trigger:
  - platform: webhook
    webhook_id: start-bob
  condition: []
  action:
  - data:
      entity_id: vacuum.bob
    service: vacuum.turn_on
- id: '1546123823141'
  alias: New Automation
  trigger:
  - platform: webhook
    webhook_id: turn_on_bob
  condition: []
  action:
  - data:
      entity_id: vacuum.bob
    service: vacuum.turn_on
- id: '1546124293346'
  alias: webhook start bob
  trigger:
  - platform: webhook
    webhook_id: start_bob
  condition: []
  action:
  - data:
      entity_id: vacuum.bob
    service: vacuum.turn_on
- id: '1546124357473'
  alias: New Automation
  trigger:
  - platform: webhook
    webhook_id: bob
  condition: []
  action:
  - data:
      entity_id: vacuum.bob
    service: vacuum.start
- id: '1546124520562'
  alias: New Automation
  trigger:
  - platform: webhook
    webhook_id: ''
  condition: []
  action:
  - data:
      entity_id: vacuum.bob
    service: vacuum.turn_on
- id: '1546124633157'
  alias: New Automation
  trigger:
  - platform: webhook
    webhook_id: ''
  condition: []
  action:
  - data:
      entity_id: vacuum.bob
    service: vacuum.turn_on
