homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat
  longitude: !secret long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes

# Enables configuration UI
config:

# Enables Homeassistant Cloud Component
cloud:

rest_command:
#Connecto Octopi to Printer
  octopi_connect:
    url: 'http://192.168.1.34/api/connection'
    method: post
    headers: 
      X-Api-Key: !secret octoprint_api
    content_type: 'application/json'
    payload: >-
      {
        "command": "connect"
      }

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123
  api_password: !secret dns_pass
  use_x_forwarded_for: True
  trusted_proxies:
    - 127.0.0.1
    - 192.168.1.1

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Logger Setup
logger:
  default: warning
  logs:
    homeassistant.components.http.ban: warning
    urllib3.connectionpool: error


# Roomba tracker
vacuum:
  - platform: roomba
    host: 192.168.1.215
    name: Bob
    username: !secret vac_user
    password: !secret vac_pass

# Device Tracker Component
device_tracker:

# Unifi WAP Device Tracker
  - platform: unifi_direct
    host: 192.168.1.31
    username: !secret unifi_user
    password: !secret unifi

#Bluetooth Tracker
  - platform: bluetooth_tracker
    new_device_defaults:
      track_new_devices: false

# Google Maps Tracker
  - platform: google_maps
    username: !secret google_maps_user
    password: !secret google_maps_password

# Text to speech
tts:
  - platform: google

# Zwave Tracker
zwave:
    usb_path: /dev/zwave
    network_key: !secret zwave_net_key

# Zigbee Tracker
zha:
    usb_path: /dev/zigbee
    database_path: /home/homeassistant/.homeassistant/zigbee.db

# MySQL Database
recorder:
  db_url: !secret db_url_password
  purge_interval: 14
  purge_keep_days: 7
  exclude:
    domains:
      - automation
      - updater
      - time
      - calendar
      - group
      - script
      - sun
      - binary_sensor
    entities:
      - camera.iss
      - input_select.jessica_status_dropdown
      - input_select.tommy_status_dropdown
      - sensor.pws_alerts
      - sensor.pws_weather_1d
      - sensor.pws_weather_1n
      - sensor.pws_weather_2d
      - sensor.pws_weather_2n
      - sensor.pws_weather_3d
      - sensor.pws_weather_3n
      - sensor.pws_weather_4d
      - sensor.pws_weather_4n
      - sensor.pws_temp_f
      - sensor.pws_temp_high_1d_f
      - sensor.pws_temp_high_record_f
      - sensor.pws_temp_low_1d_f
      - sensor.pws_temp_low_record_f
      - sensor.pws_wind_1d_mph
      - sensor.pws_wind_mph
      - sensor.time

# MQTT Component
mqtt:
  broker: 192.168.1.22
  username: !secret mqtt_user 
  password: !secret mqtt_password

# Google Push Notifications
notify:
  - name: google_push
    platform: html5
    gcm_api_key: !secret gcm_api
    gcm_sender_id: !secret gcm_sender

# IFTTT Component
ifttt:
  key: !secret ifttt_key

# Media Players Component
media_player:
  - platform: kodi
    host: 192.168.1.174
    name: Living Room TV
    port: 8080

#Octoprint Component
octoprint:
  host: 192.168.1.34
  api_key: !secret octoprint_api
  bed: true
  number_of_tools: 1

# Google Component
google:
  client_id: !secret client_id
  client_secret: !secret client_secret

# Show ISS space station on google maps
camera:
  - platform: generic
    name: ISS
    still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.binary_sensor.iss.attributes.lat }},{{ states.binary_sensor.iss.attributes.long }}&zoom=5&size=500x500&maptype=roadmap&markers=color:blue%7Clabel:P%7C{{ states.binary_sensor.iss.attributes.lat }},{{ states.binary_sensor.iss.attributes.long }}
    limit_refetch_to_url_change: true

  - platform: mjpeg
    name: octo_print_camera
    mjpeg_url: http://192.168.1.34/webcam/?action=stream

# Dominos Component
dominos:
  country_code: us
  first_name: !secret first_name
  last_name: !secret last_name
  email: !secret email
  phone: !secret phone_number
  address: !secret address
  show_menu: 1

panel_custom:
# Dominos Panel in Front End
  - name: dominos
    sidebar_title: Dominos
    sidebar_icon: mdi:pizza
    url_path: dominos

# Node-Red Panel
panel_iframe:
  nodered:
    title: 'Node-Red'
    icon: 'mdi:shuffle-variant'
    url: 'http://192.168.1.22:1880/'

input_select:
# Input Select for Jessica
  jessica_status_dropdown:
    name: Jessica
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away

#Input Select for Tommy
  tommy_status_dropdown:
    name: Tommy
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away

#Input Select from Lexi
  lexi_status_dropdown:
    name: Lexi
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away

zone:
# Jessica Work Zone
#  - name: Jessica Work
#    latitude: !secret jessica_work_lat
#    longitude: !secret jessica_work_long
#    radius: 200
#    icon: mdi:worker

# Tommy Work Zone
  - name: Tommy Work
    latitude: !secret tommy_work_lat
    longitude: !secret tommy_work_long
    radius: 500
    icon: mdi:worker

switch:
#TV Backlight power
  - platform: mqtt
    name: "TV Lights Power"
    command_topic: "cmnd/tvlights/power"
    state_topic: "stat/tvlights/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

#Master Bedroom Fan Switch
  - platform: mqtt
    name: "Master Bedroom Fan"
    command_topic: "cmnd/master_bedroom/power"
    state_topic: "stat/master_bedroom/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

#3D Printer Power
  - platform: mqtt
    name: "3D Printer Power"
    command_topic: "cmnd/3dprinter/power"
    state_topic: "stat/3dprinter/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

#Dummy MQTT switch to disable morning routine after running once
  - platform: mqtt
    name: "Morning Alert"
    state_topic: 'boolean/morning_alert'
    command_topic: 'boolean/morning_alert'
    payload_on: 'on'
    payload_off: 'off'
    retain: true

variable:
# Last Motion Variable
  last_motion:
    name: Last Room Motion Downstairs
    value: 'Unknown'
    restore: true
    attributes:
      icon: mdi:map-marker
      name: "Last Motion"

cover:
#Garage Door Cover
  - platform: mqtt
    name: "garage_door"
    state_topic: "sensor/garage/state1"
    command_topic: "sensor/garage/action1"
    payload_open: "OPEN"
    payload_close: "OPEN"
    payload_stop: "OPEN"
    state_open: "open"
    state_closed: "closed"
    optomistic: false
    retain: false

calendar:
#Todoist Calendar
  - platform: todoist
    token: !secret todoist_API
    custom_projects:
      - name: 'Due Today'
        due_date_days: 0
      - name: 'Due This Week'
        due_date_days: 7

group: !include groups.yaml
automation: !include_dir_merge_list automations/
script: !include scripts.yaml
sensor: !include_dir_merge_list sensor/
binary_sensor: !include_dir_merge_list binary_sensor/
shell_command: !include shellcommand.yaml

