homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat
  longitude: !secret long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  # Customization file
  customize: !include customize.yaml
  
  packages: !include_dir_named packages
  
  auth_providers:
   - type: homeassistant
   - type: legacy_api_password
     api_password: !secret dns_pass
   - type: trusted_networks
     trusted_networks:
       - 127.0.0.1
       - 192.168.1.0/24

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes
  javascript_version: latest

# Enables configuration UI
config:

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - 816032519
      - 846016601

default_config:

shopping_list:

circadian_lighting:

# Enables Homeassistant Cloud Component
cloud:
  google_actions:
    filter:
      exclude_domains:
        - group
        - sensor
        - vacuum
        - script

#system health check
system_health:

tplink:
  discovery: true
  light:
    - host: 192.168.1.43
#lovelace config mode
lovelace:
  mode: yaml

#rest command
rest_command:
  #Connecto Octopi to Printer
  octopi_connect:
    url: 'http://192.168.1.34/api/connection'
    method: post
    headers: 
      X-Api-Key: !secret octoprint_api
    content_type: 'application/json'
    payload: >-
      {
        "command": "connect"
      }

#http Component
http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123
  use_x_forwarded_for: True
  trusted_proxies:
    - 127.0.0.1
    - 192.168.1.1

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:
ssdp:
zeroconf:
# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Logger Setup
logger:
  default: warning
  logs:
    homeassistant.components.http.ban: warning
    urllib3.connectionpool: error

#custom_updater device for custom components
custom_updater:
  track:
     - cards
     - components
     - python_scripts
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
    - https://raw.githubusercontent.com/iammexx/home-assistant-config/master/ui/darksky/version.json
    - https://raw.githubusercontent.com/atomic7777/atomic_calendar/master/tracker.json

# Roomba tracker
vacuum:
  - platform: roomba
    host: 192.168.1.215
    name: Bob
    username: !secret vac_user
    password: !secret vac_pass
    map: true
    map_dir: www/roomba
    icon_dir: www/roomba/res

# Device Tracker Component
device_tracker:

  # Unifi WAP Device Tracker
  - platform: unifi_direct
    host: 192.168.1.31
    username: !secret unifi_user
    password: !secret unifi
    new_device_defaults:
      track_new_devices: false

  #Bluetooth Tracker
  - platform: bluetooth_tracker
    new_device_defaults:
      track_new_devices: false

  # Google Maps Tracker
  - platform: google_maps
    username: !secret google_maps_user
    password: !secret google_maps_password

  # NMAP Tracker
  - platform: nmap_tracker
    hosts: !secret network
    exclude:
     - !secret hass_ip
    scan_options: " --privileged -sP "
    home_interval: 5
    interval_seconds: 120

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Zwave Tracker
zwave:
    usb_path: /dev/zwave
    network_key: !secret zwave_net_key

# Zigbee Tracker
zha:
    usb_path: /dev/zigbee
    database_path: /home/homeassistant/.homeassistant/zigbee.db

# MySQL Database
recorder:
  db_url: !secret db_url_password
  purge_interval: 14
  purge_keep_days: 7
  include:
    domains:
      - switch
      - vacuum
      - zwave
      - media_player
    entities:
      - light.bar_light
      - sensor.common_area_humidity
      - sensor.common_area_brightness
      - sensor.common_area_motion
      - sensor.common_area_temperature
      - sensor.dining_room_humidity
      - sensor.dining_room_brightness
      - binary_sensor.dining_room_motion
      - sensor.dining_room_temperature
      - sensor.garage_door_template
      - sensor.garage_humidity
      - sensor.garage_brightness
      - binary_sensor.garage_motion
      - sensor.garage_temperature
      - sensor.htpc_idle
      - sensor.glances
      - sensor.google_travel_time_driving
      - sensor.jessica_status
      - sensor.kitchen_feels_like
      - sensor.kitchen_humidity
      - sensor.kitchen_brightness
      - binary_sensor.kitchen_motion
      - sensor.kitchen_temperature
      - sensor.lexixboxone
      - sensor.living_room_humidity_combo
      - sensor.living_room_brightness_combo
      - sensor.living_room_motion_combo
      - sensor.living_room_temperature_combo
      - sensor.master_bedroom_humidity
      - sensor.master_bedroom_brightness
      - binary_sensor.master_bedroom_motion
      - sensor.master_bedroom_temperature
      - sensor.nws_alert_count_filtered
      - sensor.ps3
      - sensor.server_ups_battery_charge
      - sensor.server_ups_battery_runtime
      - sensor.server_ups_battery_voltage
      - sensor.server_ups_input_voltage
      - sensor.server_ups_load
      - sensor.server_ups_nominal_real_power
      - sensor.server_ups_output_voltage
      - sensor.server_ups_self_test_result
      - sensor.server_ups_status
      - sensor.speedtest_download
      - sensor.speedtest_ping
      - sensor.speedtest_upload
      - sensor.tommy_status
      - sensor.xbox360
      - sensor.xboxone
      - sensor.taylex15
      - person.tommy
      - person.jessica
      - variable.last_motion
      - sensor.plex
      - binary_sensor.computer_room_motion
      - sensor.computer_room_brightness
      - sensor.average_temp
      - sensor.average_humidity
      - sensor.front_room_brightness
      - sensor.front_room_humidity
      - binary_sensor.front_room_motion
      - sensor.front_room_temperature

#speedtest component
speedtestdotnet:

#person component
person:

#influxdb
influxdb:
  host: localhost
  include:
    domains:
      - sensor
      - media_player
      - switch
      - light

# MQTT Component
mqtt:
  broker: 192.168.1.22
  username: !secret mqtt_user 
  password: !secret mqtt_password

#Push Notifications
notify:
  - name: telegram
    platform: telegram
    chat_id: 816032519
    
# IFTTT Component
ifttt:
  key: !secret ifttt_key

# Media Players Component
media_player:
  - platform: kodi
    host: 192.168.1.174
    name: Living Room TV
    port: 8080

  - platform: xboxone
    device: !secret lexi_xboxone_device_id
    name: Lexi Xbox One

#Octoprint Component
octoprint:
  host: 192.168.1.34
  api_key: !secret octoprint_api
  bed: true
  number_of_tools: 1

# Google Component
google:
  client_id: !secret client_id
  client_secret: !secret client_secret
  track_new_calendar: true

#stream Component
stream:

# Camera Component
camera:
  - platform: mjpeg
    name: octo_print_camera
    mjpeg_url: http://192.168.1.34/webcam/?action=stream
    
  - platform: mjpeg
    name: Back Porch
    mjpeg_url: http://192.168.1.42:8080/?action=stream

# Dominos Component
dominos:
  country_code: us
  first_name: !secret first_name
  last_name: !secret last_name
  email: !secret email
  phone: !secret phone_number
  address: !secret address
  show_menu: 1

#custom Panel
panel_custom:
  # Dominos Panel in Front End
  - name: dominos
    sidebar_title: Dominos
    sidebar_icon: mdi:pizza
    url_path: dominos

#  Panel IFrame
panel_iframe:
  nodered:
    title: 'Node-Red'
    icon: 'mdi:shuffle-variant'
    url: 'http://192.168.1.22:1880/'
  grafana:
    title: 'Grafana'
    icon: mdi:chart-bar-stacked
    url: 'http://192.168.1.22:3000'
  roomba_clean:
    title: 'Roomba Clean Map'
    icon: mdi:robot-vacuum
    url: 'http://192.168.1.22:8123/local/roomba/map_notext.png'
    
#Zones
zone:
  # Jessica Work Zone
#  - name: Jessica Work
#    latitude: !secret jessica_work_lat
#    longitude: !secret jessica_work_long
#    radius: 200
#    icon: mdi:worker

  # Tommy Work Zone
  - name: Tommy Work
    latitude: !secret tommy_work_lat
    longitude: !secret tommy_work_long
    radius: 1000
    icon: mdi:worker
    
  #Win-Dixie for shopping list component
  - name: Win-Dixie
    latitude: !secret win_dixie_lat
    longitude: !secret win_dixie_long
    radius: 150
    icon: mdi:cart

#Switch
switch:
  #circadian_lighting custom component
  - platform: circadian_lighting
    min_brightness: 5
    lights_ct:
      - light.bar_light

  #Outside Christmas lights switch
  - platform: mqtt
    name: "Christmas Outside Lights"
    command_topic: "cmnd/sonoff1/power"
    state_topic: "stat/sonoff1/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

  #TV Backlight power
  - platform: mqtt
    name: "TV Lights Power"
    command_topic: "cmnd/tvlights/power"
    state_topic: "stat/tvlights/POWER1"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

  #Master Bedroom Fan Switch
  - platform: mqtt
    name: "Master Bedroom Fan"
    command_topic: "cmnd/master_bedroom/power"
    state_topic: "stat/master_bedroom/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

  #3D Printer Power
  - platform: mqtt
    name: "3D Printer Power"
    command_topic: "cmnd/3dprinter/power"
    state_topic: "stat/3dprinter/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

  #Dummy MQTT switch to disable morning routine after running once
  - platform: mqtt
    name: "Morning Alert"
    state_topic: 'boolean/morning_alert'
    command_topic: 'boolean/morning_alert'
    payload_on: 'on'
    payload_off: 'off'
    retain: true

  #Guest Mode Switch
  - platform: mqtt
    name: "Guest Mode"
    state_topic: 'boolean/guest_mode'
    command_topic: 'boolean/guest_mode'
    payload_on: 'on'
    payload_off: 'off'
    retain: true

  #Couch Sleeper Switch
  - platform: mqtt
    name: "Couch Sleeper"
    state_topic: 'boolean/couch_sleeper'
    command_topic: 'boolean/couch_sleeper'
    payload_on: 'on'
    payload_off: 'off'
    retain: true

  #Coffee Pot Switch
  - platform: mqtt
    name: "Coffee Pot"
    state_topic: "coffeepot/switch"
    command_topic: "coffeepot/switch"
    payload_on: "ON"
    payload_off: "OFF"
    state_on: "ON"
    state_off: "OFF"
    optimistic: false
    qos: 0
    retain: false

#Custom Variable Component
variable:
  # Last Motion Variable
  last_motion:
    name: Last Room Motion Common Area
    value: 'Unknown'
    restore: true
    attributes:
      icon: mdi:map-marker
      name: "Last Motion"

  #tommy status variable
  tommy_status:
    name: tommy status
    restore: true
    attributes:
      icon: mdi:map-marker
      name: "tommy status"

  #jessica status variable
  jessica_status:
    name: jessica status
    restore: true
    attributes:
      icon: mdi:map-marker
      name: "jessica status"

  #lexi status variable
  lexi_status:
    name: lexi status
    restore: true
    attributes:
      icon: mdi:map-marker
      name: "lexi status"

#cover:
   #Garage Door Cover
#  - platform: mqtt
#    name: "garage_door"
#    state_topic: "sensor/garage/state1"
#    command_topic: "sensor/garage/action1"
#    payload_open: "OPEN"
#    payload_close: "OPEN"
#    payload_stop: "OPEN"
#    state_open: "open"
#    state_closed: "closed"
#    optomistic: false
#    retain: false

#calendar Component
calendar:
  #Todoist Calendar
  - platform: todoist
    token: !secret todoist_API
    custom_projects:
      - name: 'Due Today'
        due_date_days: 0
      - name: 'Due This Week'
        due_date_days: 7

#input select
input_select:
  which_holiday:
    name: Which Holiday Decorations are Put Up
    options:
      - None
      - Christmas
      - Halloween
      - Thanksgiving

  bedroom_fan_automation:
    name: Should Bedroom Fan Automatically Turn On
    options:
      - 'Yes'
      - 'No'

  is_coffee_pot_setup:
    name: Is the Coffee Pot Setup
    options:
      - 'Yes'
      - 'No'

  wake_time:
    name: Wake Time
    options:
      - '01:00'
      - '01:30'
      - '02:00'
      - '02:30'
      - '03:00'
      - '03:30'
      - '04:00'
      - '04:30'
      - '05:00'
      - '05:30'
      - '06:00'
      - '06:30'
      - '07:00'
      - '07:30'
      - '08:00'
      - '08:30'
      - '09:00'
      - '09:30'
      - '10:00'
      - '10:30'
      - '11:00'
      - '11:30'
      - '12:00'
      - '12:30'
      - '13:00'
      - '13:30'
      - '14:00'
      - '14:30'
      - '15:00'
      - '15:30'
      - '16:00'
      - '16:30'
      - '17:00'
      - '17:30'
      - '18:00'
      - '18:30'
      - '19:00'
      - '19:30'
      - '20:00'
      - '20:30'
      - '21:00'
      - '21:30'
      - '22:00'
      - '22:30'
      - '23:00'
      - '23:30'
      - '00:00'
      - '00:30'

  bed_time:
    name: Bed Time
    options:
      - '01:00'
      - '01:30'
      - '02:00'
      - '02:30'
      - '03:00'
      - '03:30'
      - '04:00'
      - '04:30'
      - '05:00'
      - '05:30'
      - '06:00'
      - '06:30'
      - '07:00'
      - '07:30'
      - '08:00'
      - '08:30'
      - '09:00'
      - '09:30'
      - '10:00'
      - '10:30'
      - '11:00'
      - '11:30'
      - '12:00'
      - '12:30'
      - '13:00'
      - '13:30'
      - '14:00'
      - '14:30'
      - '15:00'
      - '15:30'
      - '16:00'
      - '16:30'
      - '17:00'
      - '17:30'
      - '18:00'
      - '18:30'
      - '19:00'
      - '19:30'
      - '20:00'
      - '20:30'
      - '21:00'
      - '21:30'
      - '22:00'
      - '22:30'
      - '23:00'
      - '23:30'
      - '00:00'
      - '00:30'

#Weather component
weather:
  - platform: darksky
    api_key: !secret dark_sky

#includes
group: !include groups.yaml
automation: !include_dir_merge_list automations/
script: !include scripts.yaml
sensor: !include_dir_merge_list sensor/
binary_sensor: !include_dir_merge_list binary_sensor/
shell_command: !include shellcommand.yaml
