title: Home
views:
  - title: Kitchen
      cards:
        - type: entities
          title: Kitchen Sensors
          show_header_toggle: true
          entities:
            - sensor.kitchen_light_level
            - sensor.kitchen_humidity
            - sensor.kitchen_temperature
            - sensor.kitchen_feels_like
            - sensor.kitchen_motion
        - type: media-control
          entity: media_player.kitchen_speaker