title: House
resources:
  - url: /local/mini-media-player-bundle.js?v=0.9.8
    type: module
  - url: /local/tracker-card.js?v=0
    type: js
  - url: /local/dark-sky-weather-card.js?v=0
    type: js
views:
  - title: Switches/Lights
    badges:
      - sensor.time
      - sensor.day
      - sensor.month
      - sun.sun
      - binary_sensor.iss
    cards:
      - type: light
        entity: light.bar_light
        name: Bar Light
      - type: entities
        title: Switches
        show_header_toggle: false
        entities:
          - switch.3d_printer_power
          - switch.christmas_outside_lights
          - switch.christmas_tree_lights
          - switch.fluxer
          - switch.inflatables
          - switch.master_bedroom_fan
          - switch.morning_alert
          - switch.seasonal_lights
          - switch.tv_lights_power
      - type: entities
        title: Bar Light Adjustment
        show_header_toggle: false
        entities:
          - light.bar_light
  - title: Common Areas
    badges:
      - sensor.time
      - sensor.day
      - sensor.month
      - sun.sun
      - binary_sensor.iss
      - sensor.plex
      - sensor.ups
    cards:
      - type: entities
        title: Common Area Sensors
        show_header_toggle: false
        entities:
          - sensor.common_area_temperature
          - sensor.common_area_feels_like
          - sensor.common_area_humidity
          - sensor.common_area_light_level
          - sensor.common_area_motion
          - variable.last_motion
          - sensor.glances
      - type: light
        entity: light.bar_light
        name: Bar Light
      - type: entities
        title: Bar Light Adjustment
        show_header_toggle: false
        entities:
          - light.bar_light
      - type: entities
        title: TV Lights Power
        show_header_toggle: false
        entities:
          - switch.tv_lights_power
      - type: entities
        title: Gaming Systems
        show_header_toggle: false
        entities:
          - sensor.xbox360
          - sensor.xboxone
          - sensor.ps3
          - sensor.switch
          - sensor.lexixboxone
      - type: entities
        title: Vacuum
        show_header_toggle: false
        entities:
          - vacuum.bob
      - type: vertical-stack
        cards:
          - type: custom:mini-media-player
            entity: media_player.downstairs
            icon: mdi:speaker-wireless
            artwork_border: true
            show_source: true
          - type: custom:mini-media-player
            entity: media_player.kitchen_speaker
            icon: mdi:speaker-wireless
            artwork_border: true
            show_source: true
          - type: custom:mini-media-player
            entity: media_player.googlehome3446
            icon: mdi:speaker-wireless
            artwork_border: true
            show_source: true
          - type: custom:mini-media-player
            entity: media_player.living_room_tv
            icon: mdi:television-box
            artwork_border: true
            show_source: true
          - type: custom:mini-media-player
            entity: media_player.chrome_3
            icon: mdi:television-box
            artwork_border: true
            show_source: true
  - title: Bedrooms
    badges:
      - sensor.time
      - sensor.day
      - sensor.month
      - sun.sun
      - binary_sensor.iss
      - sensor.taylex15
    cards:
      - type: entities
        title: Master Bedroom Sensors
        show_header_toggle: false
        entities:
          - sensor.master_bed_room_temperature
          - sensor.master_bed_room_feels_like
          - sensor.master_bed_room_humidity
          - sensor.master_bed_room_light_level
          - sensor.master_bed_room_motion
      - type: entities
        title: Master Bedroom Sensors
        show_header_toggle: false
        entities:
          - switch.master_bedroom_fan
      - type: custom:mini-media-player
        entity: media_player.master_bath
        icon: mdi:speaker-wireless
        artwork_border: true
        show_source: true
      - type: custom:mini-media-player
        entity: media_player.roku_guest_bedroom
        icon: mdi:television-box
        artwork_border: true
        show_source: true
  - title: Dining Room
    badges:
      - sensor.time
      - sensor.day
      - sensor.month
      - sun.sun
      - binary_sensor.iss
    cards:
      - type: entities
        title: Dining Room Sensors
        show_header_toggle: false
        entities:
          - sensor.dining_room_temperature
          - sensor.dining_room_feels_like
          - sensor.dining_room_humidity
          - sensor.dining_room_light_level
          - sensor.dining_room_motion_2
  - title: Garage
    badges:
      - sensor.time
      - sensor.day
      - sensor.month
      - sun.sun
      - binary_sensor.iss
    cards:
      - type: entities
        title: Garage Sensors
        show_header_toggle: false
        entities:
          - sensor.garage_temperature
          - sensor.garage_feels_like
          - sensor.garage_humidity
          - sensor.garage_light_level
          - sensor.garage_motion
      - type: entities
        title: 3D Printer Status
        show_header_toggle: false
        entities:
          - binary_sensor.octoprint_printing
          - binary_sensor.octoprint_printing_error
          - sensor.octoprint_actual_bed_temp
          - sensor.octoprint_actual_tool0_temp
          - sensor.octoprint_current_state
          - sensor.octoprint_job_percentage
          - sensor.octoprint_target_bed_temp
          - sensor.octoprint_target_tool0_temp
          - sensor.octoprint_time_elapsed
          - sensor.octoprint_time_remaining
          - camera.octo_print_camera
      - type: entities
        title: 3D Printer Power
        show_header_toggle: false
        entities:
          - switch.3d_printer_power
      - type: custom:mini-media-player
        entity: media_player.garage_chromecast
        icon: mdi:television-box
        artwork_border: true
        show_source: true
  - title: Kitchen
    badges:
      - sensor.time
      - sensor.day
      - sensor.month
      - sun.sun
      - binary_sensor.iss
    cards:
      - type: entities
        title: Kitchen Sensors
        show_header_toggle: false
        entities:
          - sensor.kitchen_temperature
          - sensor.kitchen_feels_like
          - sensor.kitchen_humidity
          - sensor.kitchen_light_level
          - sensor.kitchen_motion
      - type: custom:mini-media-player
        entity: media_player.kitchen_speaker
        icon: mdi:speaker-wireless
        artwork_border: true
        show_source: true
      - type: light
        entity: light.bar_light
        name: Bar Light
      - type: entities
        title: Bar Light Adjustment
        show_header_toggle: false
        entities:
          - light.bar_light
  - title: Living Room
    badges:
      - sensor.time
      - sensor.day
      - sensor.month
      - sun.sun
      - binary_sensor.iss
      - sensor.plex
    cards:
      - type: light
        entity: light.bar_light
        name: Bar Light
      - type: entities
        title: Bar Light Adjustment
        show_header_toggle: false
        entities:
          - light.bar_light
      - type: entities
        title: Living Room Sensors
        show_header_toggle: false
        entities:
          - sensor.living_room_temperature_combo
          - sensor.living_room_feels_like_combo
          - sensor.living_room_humidity_combo
          - sensor.living_room_light_level_combo
          - sensor.living_room_motion_combo
          - sensor.glances
      - type: entities
        title: TV Lights Power
        show_header_toggle: false
        entities:
          - switch.tv_lights_power
      - type: entities
        title: Gaming Systems
        show_header_toggle: false
        entities:
          - sensor.xbox360
          - sensor.xboxone
          - sensor.ps3
          - sensor.switch
          - sensor.lexixboxone
      - type: custom:mini-media-player
        entity: media_player.googlehome3446
        icon: mdi:speaker-wireless
        artwork_border: true
        show_source: true
      - type: custom:mini-media-player
        entity: media_player.living_room_tv
        icon: mdi:television-box
        artwork_border: true
        show_source: true
  - title: Master Bedroom
    badges:
      - sensor.time
      - sensor.day
      - sensor.month
      - sun.sun
      - binary_sensor.iss
    cards:
      - type: entities
        title: Master Bedroom Sensors
        show_header_toggle: false
        entities:
          - sensor.master_bed_room_temperature
          - sensor.master_bed_room_feels_like
          - sensor.master_bed_room_humidity
          - sensor.master_bed_room_light_level
          - sensor.master_bed_room_motion
      - type: entities
        title: Master Bedroom Sensors
        show_header_toggle: false
        entities:
          - switch.master_bedroom_fan
      - type: custom:mini-media-player
        entity: media_player.master_bath
        icon: mdi:speaker-wireless
        artwork_border: true
        show_source: true
  - title: Guest Bedroom
    badges:
      - sensor.time
      - sensor.day
      - sensor.month
      - sun.sun
      - binary_sensor.iss
    cards:
      - type: custom:mini-media-player
        entity: media_player.roku_guest_bedroom
        icon: mdi:television-box
        artwork_border: true
        show_source: true
  - title: Front Office
    badges:
      - sensor.time
      - sensor.day
      - sensor.month
      - sun.sun
      - binary_sensor.iss
  - title: People
    badges:
      - sensor.time
      - sensor.day
      - sensor.month
      - sun.sun
      - binary_sensor.iss
      - binary_sensor.workday_sensor
      - sensor.google_travel_time__driving
      - sensor.taylex15
    cards:
      - type: entity-filter
        show_empty: false
        entities:
          - sensor.jessica_status
          - sensor.tommy_status
        state_filter:
          - Home
          - Just Arrived
        card: 
          type: glance
          title: People at home
      - type: entity-filter
        show_empty: false
        entities:
          - sensor.jessica_status
          - sensor.tommy_status
        state_filter:
          - Away
          - Extended Away
          - Just Left
        card: 
          type: glance
          title: People That Are Away
  - title: Weather
    cards:
      - type: weather-forecast
        entity: weather.dark_sky
  - title: Automations/Scripts
    badges:
      - sensor.time
      - sensor.day
      - sensor.month
      - sun.sun
      - binary_sensor.iss
    cards:
      - type: entities
        title: Automations
        show_header_toggle: false
        entities:
          - automation.3d_printer_is_left_on
          - automation.3d_printer_job_50_complete
          - automation.3d_printer_job_complete
          - automation.activate_morning_routine
          - automation.after_christmas
          - automation.christmas_eve
          - automation.connect_octopi_to_printer
          - automation.darker_theme_at_sunset
          - automation.downstairs_unavailable
          - automation.flux_switch_on_at_startup
          - automation.heal_z_wave_at_332am
          - automation.holiday_select_automation_turn_off
          - automation.holiday_select_automation_turn_on
          - automation.is_lexi_off_xbox
          - automation.is_lexi_on_xbox
          - automation.lexi_brush_teeth
          - automation.lighter_theme_at_sunrise
          - automation.mark_person_as_away
          - automation.mark_person_as_extended_away
          - automation.mark_person_as_home
          - automation.mark_person_as_just_arrived
          - automation.mark_person_as_just_left
          - automation.match_tv_lights_to_htpc_state
          - automation.recycling_day
          - automation.reset_morning_routine_switch
          - automation.send_bob_home
          - automation.test_z_wave_at_230am
          - automation.trash_day
          - automation.tts_and_notify_weather_alert
          - automation.turn_off_back_porch_lights
          - automation.turn_off_bar_light_at_night
          - automation.turn_off_bedroom_fan_weekday
          - automation.turn_off_bedroom_fan_weekend
          - automation.turn_off_christmas_tree
          - automation.turn_off_outside_decorations_christmas
          - automation.turn_off_outside_decorations_halloween
          - automation.turn_off_outside_decorations_thanksgiving
          - automation.turn_on_back_porch_lights
          - automation.turn_on_bar_light_with_morning_automation
          - automation.turn_on_bedroom_fan
          - automation.turn_on_bob
          - automation.turn_on_christmas_tree
          - automation.turn_on_oustide_decorations_christmas
          - automation.turn_on_oustide_decorations_halloween
          - automation.turn_on_oustide_decorations_thanksgiving
          - automation.update_dowdom_sensors
          - automation.update_last_motion
          - automation.update_people_on_restart
          - automation.wx_alert_notification
      - type: entities
        title: Scripts
        show_header_toggle: false
        entities:
          - script.download_movie
          - script.download_option
          - script.morning_greeting
          - script.notifyonwxalert
          - script.search_movie
  - title: Status
    badges:
      - sensor.time
      - sensor.day
      - sensor.month
      - sun.sun
      - binary_sensor.iss
      - sensor.speedtest_download
      - sensor.speedtest_ping
      - sensor.speedtest_upload
    cards:
      - type: entities
        title: Home Assistant Status
        show_header_toggle: false
        entities:
          - sensor.memory_free
          - sensor.memory_use_percent
          - sensor.processor_use
          - sensor.disk_use_percent_home
          - sensor.last_boot
      - type: entities
        title: Server UPS Status
        show_header_toggle: false
        entities:
          - sensor.server_ups_status
          - sensor.server_ups_battery_charge
          - sensor.server_ups_battery_runtime
          - sensor.server_ups_battery_voltage
          - sensor.server_ups_input_voltage
          - sensor.server_ups_load
          - sensor.server_ups_nominal_real_power
          - sensor.server_ups_output_voltage
          - sensor.server_ups_selftest_result
      - type: entities
        title: Calendars
        show_header_toggle: false
        entities:
          - calendar.due_this_week
          - calendar.due_today
          - calendar.errands
          - calendar.holidays_in_united_states
          - calendar.inbox
          - calendar.main
          - calendar.movies_to_watch
          - calendar.personal
          - calendar.shopping
          - calendar.work
      - type: entities
        title: Z-Wave
        show_header_toggle: false
        entities:
          - zwave.ge_14284_outdoor_smart_switch
          - zwave.ge_14284_outdoor_smart_switch_2
          - zwave.honeywell_unknown_type5052_id3033
          - zwave.kitchen_range_extender
          - zwave.living_room_range_extender
          - zwave.sigma_designs_uzb_zwave_usb_adapter
      - type: entities
        title: Network
        show_header_toggle: false
        entities:
          - sensor.pfsense
          - sensor.freenas
          - sensor.proxmox
          - sensor.guestap
          - sensor.unifiap
          - sensor.obitalk
          - sensor.ombi
          - sensor.owncloud
          - sensor.plexserver
          - sensor.radarr
          - sensor.sabnzbd
          - sensor.sonarr
          - sensor.torrent
          - sensor.tvheadend
          - sensor.unificontroller
      - type: entities
        title: Weblinks
        show_header_toggle: false
        entities:
          - type: weblink
            name: Router
            url: 'https://pfsense.home:4443/'
          - type: weblink
            name: Proxmox
            url: 'https://192.168.1.11:8006/#v1:0:=node%2Fproxmox:4:39:::::2'
          - type: weblink
            name: Unifi Controller
            url: 'https://192.168.1.21:8443/manage/account/login?redirect=%2Fmanage%2Fsite%2Fdefault%2Fdevices%2F1%2F50%2Fuap'
          - type: weblink
            name: FreeNAS
            url: 'http://192.168.1.10/account/login/?next=/'
          - type: weblink
            name: Plex
            url: 'http://192.168.1.18:32400/web/index.html#'
          - type: weblink
            name: Ombi
            url: 'http://192.168.1.16:5000/search'
          - type: weblink
            name: TVHeadend
            url: 'http://192.168.1.15:9981/extjs.html'
          - type: weblink
            name: Own Cloud
            url: 'https://owncloud.bell-family.cc/index.php/apps/files/'
          - type: weblink
            name: Transmission
            url: 'https://192.168.1.20:12322/transmission/web/'
          - type: weblink
            name: SabNZBD
            url: ' http://192.168.1.12:8080/sabnzbd/'
          - type: weblink
            name: Sonarr
            url: 'http://192.168.1.13:8989/'
          - type: weblink
            name: Radarr
            url: 'http://192.168.1.14:7878/'
          - type: weblink
            name: OctoPrint
            url: 'https://octopi.local/'
          - type: weblink
            name: ObiTalk
            url: 'http://192.168.1.33/'          
  - title: Settings
    cards:
      - type: entities
        title: Which Decorations Are Put Up
        show_header_toggle: false
        entities:
          - input_select.which_holiday
      - type: custom:tracker-card
        title: Custom Card Updates
        trackers:
          - sensor.custom_card_tracker
          - sensor.custom_component_tracker

        