title: My Awesome Home
# Exclude entities from "Unused entities" view
excluded_entities:

views:
    # View tab title.
  - title: Example
    # Optional unique id for direct access /lovelace/${id}
    id: example
    # Each view can have a different theme applied.
    theme: dark-mode
    # The cards to show on this view.
    cards:
        # The filter card will filter entities for their state
      - type: entity-filter
        entities:
          - sensor.jessica_status
          - sensor.tommy_status
          - sensor.lexi_status
        state_filter:
          - 'Home'
        card:
          type: glance
          title: People that are home

      - type: entity-filter
        entities:
          - sensor.jessica_status
          - sensor.tommy_status
          - sensor.lexi_status
        state_filter:
          - 'Away'
        show_empty: false
        card:
          type: glance
          title: People that are away

      - type: entities
        title: Living Room
        entities:
         - sensor.living_room_light_level_combo
         - sensor.living_room_humidity_combo
         - sensor.living_room_temperature_combo
         - sensor.living_room_feels_like_combo
         - sensor.living_room_motion_combo
         - sensor.glances
         - switch.tv_lights_power
         - media_player.living_room_tv

      - type: entities
        title: Kitchen
        entities:
         - sensor.kitchen_light_level
         - sensor.kitchen_humidity
         - sensor.kitchen_temperature
         - sensor.kitchen_feels_like
         - sensor.kitchen_motion

      - type: entities
        title: Dining Room
        entities:
         - sensor.dining_room_light_level
         - sensor.dining_room_humidity
         - sensor.dining_room_temperature
         - sensor.dining_room_feels_like
         - sensor.dining_room_motion

      - type: entities
        title: Garage
        entities:
         - sensor.garage_light_level
         - sensor.garage_humidity
         - sensor.garage_temperature
         - sensor.garage_feels_like
         - sensor.garage_motion
         - cover.garage_door
         - media_player.garage_chromecast

      - type: entities
        title: Master Bed Room
        entities:
         - sensor.master_bed_room_light_level
         - sensor.master_bed_room_humidity
         - sensor.master_bed_room_temperature
         - sensor.master_bed_room_feels_like
         - sensor.master_bed_room_motion

      - type: entities
        title: 3D Printer
        entities:
         - sensor.octoprint_current_state
         - sensor.octoprint_job_percentage
         - sensor.hotend_temp
         - sensor.hotend_target
         - sensor.bed_temp
         - sensor.bed_target
         - camera.octo_print_camera
         - switch.3d_printer_power

      - type: entities
        title: Weather Information
        entities:
         - sensor.pws_weather_1d_metric
         - sensor.pws_temp_high_record_f
         - sensor.pws_temp_high_1d_f
         - sensor.pws_temp_f
         - sensor.pws_temp_low_1d_f
         - sensor.pws_temp_low_record_f
         - sensor.pws_precip_1d
         - sensor.pws_precip_1d_in
         - sensor.pws_wind_mph
         - sensor.pws_wind_1d_mph
         - sensor.pws_alerts

      - type: entities
        title: Weather Forecast
        entities:
         - sensor.pws_weather_1d
         - sensor.pws_weather_1n
         - sensor.pws_weather_2d
         - sensor.pws_weather_2n
         - sensor.pws_weather_3d
         - sensor.pws_weather_3n
         - sensor.pws_weather_4d
         - sensor.pws_weather_4n


        # The markdown card will render markdown text.
      - type: markdown
        title: Lovelace
        content: >
          Welcome to your **Lovelace UI**.