#  - alias: 'Turn Off Outside Christmas Lights'
#    trigger:
#      platform: time
#      at: '22:59:00'
#    action:
#    - service: homeassistant.turn_off
#      entity_id: switch.christmas_oustide_lights

#  - alias: 'Turn On Outside Chrostmas Lights'
#    trigger:
#      platform: sun
#      event: sunset
#    action:
#    - service: homeassistant.turn_on
#      entity_id: switch.christmas_oustide_lights

#  - alias: 'Christmas Eve'
#    trigger:
#      platform: template
#      value_template: '{{ now().date() | string == "2017-12-23" }}'
#    action:
#    - service: automation.turn_off
#      entity_id: automation.turn_off_outside_christmas_lights
#      
#  - alias: 'After Christmas'
#    trigger:
#      platform: template
#      value_template: '{{ now().date() | string == "2017-12-25" }}'
#    action:
#    - service: automation.turn_on
#      entity_id: automation.turn_off_outside_christmas_lights